import type { Metadata } from 'next';
import { GeistSans } from 'geist/font';
import Navbar from './components/Navbar';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className} bg-background font-sans`}>
        <div id="side-navbar-portal-root"></div>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
